### ISSUE TITLE
Does wintersmith support partial regeneration? 

### ISSUE THREAD

**Issue by geertbrit** [jnordberg/wintersmith#228]
I'm looking for a static site generator that will allow me to do loads of static site generations per day, for loads of differerent sites. 

To save big on cost/time I'm looking for a static site generator that supports partial regeneration instead of full regeneration. Presumably this is done by keeping a Dependency Graph of documents, document partials, document collections and only update the contents in the Content Tree that are dirty themselves or are 'dependent' (by traversing the dependency graph)  on a dirty piece of content.

Is this supported in Wintersmith? 
If not, what would be the big obstacles to implementing this? I can contribute time to this feature if I'm confident Wintersmith is the way to go. 

Thannks.

**Comment by sebastienbarre** [comment]
I would be interested in that capability as well, and could also help at some point -- maybe Wintersmith could have an API hook that lets plugins implement "should this post be regenerated?" strategies.

**Comment by timaschew** [comment]
any feedback @jnordberg ?

**Comment by jnordberg** [comment]
I remember experimenting with dependency graphs and promises when writing wintersmith and deciding it wasn't worth the trouble. I found that the best way to work with the content tree (inside of templates, view logic, plugins etc) was to have it be an object that was already populated, i.e. synchronously.

We could add a 'if-modified-since' method that plugins can implement like @sebastienbarre suggests, that could improve build times but there's no getting around that the content tree needs to be loaded in to memory before anything can happen.
