### ISSUE TITLE
Looks fine when previewed, but not when built

### ISSUE THREAD

**Issue by MashyCode** [jnordberg/wintersmith#276]
Firstly, I apologise for this silly question, but I'm trying to learn how to use github to host a blog and decided to use wintersmith.

Baiscally, I can make the blog and preview it; it looks fine when I preview, however when I build the blog and view the index.html on local host, it doesn't look anything like what's shown on the preview i.e. seems like none of the css stuff has been applied. Was whether there was a step I've missed? I was following this tutorial: https://www.youtube.com/watch?v=zLenQTdgPaI (I'm using windows 7 but everything works fine).

While I'm at it, once I built the files, is it a matter of uploading all the web-file (html, blog entries) on to my github-pages repository?

**Comment by sebastienbarre** [comment]
That is because Wintersmith assumes you will be deploying what's inside ```build```, or that you will use a local webserver pointing at said directory to test it. Loading the ```index.html``` straight in a web browser (by double-clicking on it for example) will not load the CSS properly. Personally I would rather have the stylesheet be a relative path, maybe it's an easy fix to contribute. 
For example, in ```index.html```, have
```
    <link rel="stylesheet" href="css/main.css">
```
instead of:
```
    <link rel="stylesheet" href="/css/main.css">
```
and in ```articles/red-herring/```, have:
```
    <link rel="stylesheet" href="../../css/main.css">
```
instead of:
```
    <link rel="stylesheet" href="/css/main.css">
```

**Comment by jnordberg** [comment]
You can also get the urls from the content tree directly, `{{ contents.css['mystyle.css'].url }}`
